const no= [1,2,3,4,5,6,7,8,9,10]
const Firstname = ["Thompson", "Johnson","Chisom",
                   "Jide","Williams","Nancy", "Nicholas", 
                   "Ahmed", "Halima", "Richard"   ]
const Lastname = ["Anthony","Mary", "Onyeka", "Olabisi",
                    "Ajayi", "Chukwuemeka", "Uchemba", "Olayinka",
                   "Mohammed", "Adeyemi",]
const Age = [32, 23, 28, 29, 30, 27, 26, 24, 26, 41]
const Sex = ["Male", "Female",]
const Position = ["Head of Finance department", "Software Engineer", 
                  "Human Resources Manager", "Assistant Head(Software Dept)", 
                  "Head of Software Dept.", "Secretary",
                   "Software Engineer","Graphic Designer", 
                    "Senior Finance Manager", "C.E.O",]
const Date_Of_Employment = ["17/07/2014", "05/03/2019", "21/06/2016", "05/06/2016",
                            "06/09/2015", "23/08/2016", "23/02/2020", "15/08/2020",
                            "20/05/2018", "17/11/2010", ]

document.getElementById("td1a").innerHTML = no[0]
document.getElementById("td2a").innerHTML = no[1]
document.getElementById("td3a").innerHTML = no[2]
document.getElementById("td4a").innerHTML = no[3]
document.getElementById("td5a").innerHTML = no[4]
document.getElementById("td6a").innerHTML = no[5]
document.getElementById("td7a").innerHTML = no[6]
document.getElementById("td8a").innerHTML = no[7]
document.getElementById("td9a").innerHTML = no[8]
document.getElementById("td10a").innerHTML = no[9]

document.getElementById("td1b").innerHTML = Firstname[0]
document.getElementById("td2b").innerHTML = Firstname[1]
document.getElementById("td3b").innerHTML = Firstname[2]
document.getElementById("td4b").innerHTML = Firstname[3]
document.getElementById("td5b").innerHTML = Firstname[4]
document.getElementById("td6b").innerHTML = Firstname[5]
document.getElementById("td7b").innerHTML = Firstname[6]
document.getElementById("td8b").innerHTML = Firstname[7]
document.getElementById("td9b").innerHTML = Firstname[8]
document.getElementById("td10b").innerHTML = Firstname[9]

document.getElementById("td1c").innerHTML = Lastname[0]
document.getElementById("td2c").innerHTML = Lastname[1]
document.getElementById("td3c").innerHTML = Lastname[2]
document.getElementById("td4c").innerHTML = Lastname[3]
document.getElementById("td5c").innerHTML = Lastname[4]
document.getElementById("td6c").innerHTML = Lastname[5]
document.getElementById("td7c").innerHTML = Lastname[6]
document.getElementById("td8c").innerHTML = Lastname[7]
document.getElementById("td9c").innerHTML = Lastname[8]
document.getElementById("td10c").innerHTML = Lastname[9]

document.getElementById("td1d").innerHTML = Age[0]
document.getElementById("td2d").innerHTML = Age[1]
document.getElementById("td3d").innerHTML = Age[2]
document.getElementById("td4d").innerHTML = Age[3]
document.getElementById("td5d").innerHTML = Age[4]
document.getElementById("td6d").innerHTML = Age[5]
document.getElementById("td7d").innerHTML = Age[6]
document.getElementById("td8d").innerHTML = Age[7]
document.getElementById("td9d").innerHTML = Age[8]
document.getElementById("td10d").innerHTML = Age[9]

document.getElementById("td1e").innerHTML = Sex[0]
document.getElementById("td2e").innerHTML = Sex[1]
document.getElementById("td3e").innerHTML = Sex[1]
document.getElementById("td4e").innerHTML = Sex[0]
document.getElementById("td5e").innerHTML = Sex[0]
document.getElementById("td6e").innerHTML = Sex[1]
document.getElementById("td7e").innerHTML = Sex[0]
document.getElementById("td8e").innerHTML = Sex[0]
document.getElementById("td9e").innerHTML = Sex[1]
document.getElementById("td10e").innerHTML = Sex[0]

document.getElementById("td1f").innerHTML = Position[0]
document.getElementById("td2f").innerHTML = Position[1]
document.getElementById("td3f").innerHTML = Position[2]
document.getElementById("td4f").innerHTML = Position[3]
document.getElementById("td5f").innerHTML = Position[4]
document.getElementById("td6f").innerHTML = Position[5]
document.getElementById("td7f").innerHTML = Position[6]
document.getElementById("td8f").innerHTML = Position[7]
document.getElementById("td9f").innerHTML = Position[8]
document.getElementById("td10f").innerHTML = Position[9]

document.getElementById("td1g").innerHTML = Date_Of_Employment [0]
document.getElementById("td2g").innerHTML = Date_Of_Employment [1]
document.getElementById("td3g").innerHTML = Date_Of_Employment[2]
document.getElementById("td4g").innerHTML = Date_Of_Employment[3]
document.getElementById("td5g").innerHTML = Date_Of_Employment[4]
document.getElementById("td6g").innerHTML = Date_Of_Employment[5]
document.getElementById("td7g").innerHTML = Date_Of_Employment[6]
document.getElementById("td8g").innerHTML = Date_Of_Employment[7]
document.getElementById("td9g").innerHTML = Date_Of_Employment[8]
document.getElementById("td10g").innerHTML = Date_Of_Employment[9]